### PR TITLE
Allow . to be the project root

### PR DESCRIPTION
**Pull request by paaguti**
I also edit scripts outside a control version system and I wanted to be able to use LSP on individual scripts

### CODE REVIEW

**Comment by paaguti** [comment]
Alternatively, one could define a couple of hidden files you could create with `touch xxx` to mark a directory as a project root and include those in `io.get_project_root()`. I'm experimenting with that too.
I'm using `.lsp_root`, but `.prj_root` could also be a nice candidate... less LSP-oriented, right?

**Comment by paaguti** [comment]
So, I did it ;-). So far checked with my $HOME/bin, where I have "a couple" scripts and it works like a breeze.

**Comment by orbitalquark** [comment]
I'm glad you were able to get it working for you :)

If I need a directory to be recognized as a project root, I just create a '.hg' or '.git' directory there, even if I have no intention of using version control. It's easier than defining another convention, as is being done here. Too much to keep track of... I might be open to falling back on the file's directory as an LSP root, but I'm concerned that a language server would start creating metadata directories everywhere.

**Comment by paaguti** [comment]
Hmm good point :-) a couple of words in the README wouldn’t harm ;-)

/PA

Enviado desde mi iPhone

**Pull request closed without merging**
